-- =============================================================================
-- V3 — Phase 5 beneficiaries + transfer linkage on the ledger.
-- Transfer legs share one transfer_reference; the counterparty account
-- number gives history context without exposing private customer data.
-- =============================================================================

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS transfer_reference VARCHAR(32);
ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS counterparty_account_number VARCHAR(24);
CREATE INDEX IF NOT EXISTS idx_transactions_transfer_ref ON transactions (transfer_reference);

CREATE TABLE IF NOT EXISTS beneficiaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    beneficiary_account_id BIGINT NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_beneficiaries_customer_account UNIQUE (customer_id, beneficiary_account_id),
    CONSTRAINT fk_beneficiaries_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_beneficiaries_account FOREIGN KEY (beneficiary_account_id) REFERENCES accounts (id)
);

CREATE INDEX IF NOT EXISTS idx_beneficiaries_customer_id ON beneficiaries (customer_id);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_account_id ON beneficiaries (beneficiary_account_id);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_status ON beneficiaries (status);
