-- =============================================================================
-- V4 — Phase 6 fraud evaluations (append-only) + analyst alerts.
-- Evaluations are never updated: transaction_id is set only for APPROVE
-- rows; REVIEW/BLOCK attempts trace via attempted_reference. Alerts are
-- created only for REVIEW/BLOCK evaluations.
-- =============================================================================

CREATE TABLE IF NOT EXISTS fraud_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    transaction_id BIGINT,
    attempted_reference VARCHAR(40),
    transfer_reference VARCHAR(32),
    idempotency_key VARCHAR(128),
    transaction_type VARCHAR(16) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    risk_score INTEGER NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    decision VARCHAR(16) NOT NULL,
    factors_json TEXT,
    evaluation_version VARCHAR(16) NOT NULL,
    evaluation_reason VARCHAR(500),
    evaluated_by VARCHAR(64),
    evaluated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fraud_eval_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_fraud_eval_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id)
);

CREATE INDEX IF NOT EXISTS idx_fraud_eval_account_id ON fraud_evaluations (account_id);
CREATE INDEX IF NOT EXISTS idx_fraud_eval_transaction_id ON fraud_evaluations (transaction_id);
CREATE INDEX IF NOT EXISTS idx_fraud_eval_decision ON fraud_evaluations (decision);
CREATE INDEX IF NOT EXISTS idx_fraud_eval_evaluated_at ON fraud_evaluations (evaluated_at);

CREATE TABLE IF NOT EXISTS fraud_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT NOT NULL,
    transaction_id BIGINT,
    account_id BIGINT NOT NULL,
    severity VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewed_by VARCHAR(64),
    CONSTRAINT fk_fraud_alert_evaluation FOREIGN KEY (evaluation_id) REFERENCES fraud_evaluations (id),
    CONSTRAINT fk_fraud_alert_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_fraud_alert_account FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE INDEX IF NOT EXISTS idx_fraud_alert_status ON fraud_alerts (status);
CREATE INDEX IF NOT EXISTS idx_fraud_alert_severity ON fraud_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_fraud_alert_created_at ON fraud_alerts (created_at);
CREATE INDEX IF NOT EXISTS idx_fraud_alert_evaluation_id ON fraud_alerts (evaluation_id);
